FROM ghcr.io/graalvm/native-image-community:17

# Install findutils, unzip and other necessary tools
RUN microdnf install -y findutils unzip

# Download and install Gradle
RUN curl -L -o /tmp/gradle.zip https://services.gradle.org/distributions/gradle-8.10-bin.zip && \
    unzip /tmp/gradle.zip -d /opt && \
    ln -s /opt/gradle-8.10/bin/gradle /usr/local/bin/gradle && \
    rm /tmp/gradle.zip

# Set working directory
WORKDIR /workspace 